#delimit;
/*This is code to extract key-files or support tables. 
Dealer keyfile
 */


/* Part A. PLAN and Category */


odbc load, exec("select year, dnum, dlr, strt1, strt2, city, st, doi, doc from cfdbs.dealer where year>=2000 order by year;") $oracle_cxn;
destring, replace;
sort gearnm;


notes: this file was generated by dealer_key_file.do, executed on "`sysdate'";
compress;


saveold "dealer_keyfile_${today_date_string}.dta",replace version(12);

