#delimit;
/*This is code to extract key-files or support tables. 
Part A. PLAN and Category - DOne
Part B. Species Codes -DONE
Part C. Port codes

 */


/* Part A. PLAN and Category */


odbc load, exec("select gearcode, negear, gearnm from vlgear;") $oracle_cxn;
destring, replace;
sort gearnm;


notes: this file was generated by gear_key_file.do, executed on "`sysdate'";
compress;


saveold "gearcodes_keyfile.dta",replace version(12);

